package onboarding

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GenerateMinimalConfig creates a minimal config file with examples
func GenerateMinimalConfig(configPath string) error {
	configDir := filepath.Dir(configPath)
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	content := `# Nunchux Configuration
# This is a minimal config - add more apps as needed.
# See docs/configuration.md for all options.

[settings]
popup_width = 90%
popup_height = 90%

# Order section - controls menu item order
# Items listed here appear first, in this order
# Unlisted items are appended alphabetically
# [order]
# htop
# system
# configs
# taskrunner:just

# Example app (uncomment and modify):
# [app:htop]
# cmd = htop
# desc = Process viewer

# Example submenu:
# [menu:system]
# status = echo "load: $(cut -d' ' -f1 /proc/loadavg)"

# Example directory browser:
# [dirbrowser:configs]
# directory = ~/.config
# depth = 2
`

	if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	return nil
}

// GenerateDetectedConfig creates a config file with the selected tools
func GenerateDetectedConfig(configPath string, tools []Tool) error {
	configDir := filepath.Dir(configPath)
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	var sb strings.Builder

	sb.WriteString(`# Nunchux Configuration
# Generated by setup wizard
# See docs/configuration.md for all options.

[settings]
popup_width = 90%
popup_height = 90%

# Order section - controls menu item order
# Items listed here appear first, in this order
# Unlisted items are appended alphabetically
# [order]
# app_name
# submenu_name
# taskrunner:just

`)

	// Separate system tools for submenu
	var systemTools []Tool
	var otherTools []Tool
	for _, t := range tools {
		if t.Category == "system" {
			systemTools = append(systemTools, t)
		} else {
			otherTools = append(otherTools, t)
		}
	}

	// Write non-system apps
	for _, t := range otherTools {
		sb.WriteString(fmt.Sprintf("[app:%s]\n", t.Name))
		// yazi needs special handling
		if t.Cmd == "yazi" {
			sb.WriteString("cmd = tmux new-session yazi --cwd-file={tmp} \\; set status off\n")
		} else {
			sb.WriteString(fmt.Sprintf("cmd = %s\n", t.Cmd))
		}
		if t.Desc != "" {
			sb.WriteString(fmt.Sprintf("desc = %s\n", t.Desc))
		}
		sb.WriteString("\n")
	}

	// Create system submenu if there are system tools
	if len(systemTools) > 0 {
		sb.WriteString("[menu:system]\n")
		sb.WriteString("status = echo \"load: $(cut -d' ' -f1 /proc/loadavg)\"\n")
		sb.WriteString("\n")

		for _, t := range systemTools {
			sb.WriteString(fmt.Sprintf("[app:system/%s]\n", t.Name))
			sb.WriteString(fmt.Sprintf("cmd = %s\n", t.Cmd))
			if t.Desc != "" {
				sb.WriteString(fmt.Sprintf("desc = %s\n", t.Desc))
			}
			sb.WriteString("\n")
		}
	}

	// Add helpful comments
	sb.WriteString(`# Directory browsers - browse files in a directory
# [dirbrowser:configs]
# directory = ~/.config
# depth = 2
# sort = modified-folder

# Task runners - run project tasks
# [taskrunner:just]
# enabled = true
`)

	if err := os.WriteFile(configPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	return nil
}

// GetDefaultConfigPath returns the default config file path
func GetDefaultConfigPath() string {
	configDir := os.Getenv("XDG_CONFIG_HOME")
	if configDir == "" {
		home, _ := os.UserHomeDir()
		configDir = filepath.Join(home, ".config")
	}
	return filepath.Join(configDir, "nunchux", "config")
}
